#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.7.0_75
export CATALINA_HOME=$OPENSHIFT_DATA_DIR/apache-tomcat-8.0.21

if [ ! -d $JAVA_HOME ]; then
    cd $OPENSHIFT_DATA_DIR
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u75-b13/jdk-7u75-linux-x64.tar.gz
    tar xvf *.tar.gz
    rm -f *.tar.gz
fi


if [ ! -d $CATALINA_HOME ]; then
    cd $OPENSHIFT_DATA_DIR
    wget http://apache.mirrors.spacedump.net/tomcat/tomcat-8/v8.0.21/bin/apache-tomcat-8.0.21.tar.gz
    tar xvf *.tar.gz
    rm -f *.tar.gz

    cd $CATALINA_HOME
    rm -rf logs
    rm -rf webapps
    rm -rf work
    rm -rf temp
    ln -s $OPENSHIFT_DIY_LOG_DIR logs
fi

mkdir -p $OPENSHIFT_DATA_DIR/axel/images/upload
cp $OPENSHIFT_REPO_DIR/diy/server.xml $CATALINA_HOME/conf
sed -ig 's/OPENSHIFT_DIY_IP/'$OPENSHIFT_DIY_IP'/' $CATALINA_HOME/conf/server.xml
sed -ig 's/OPENSHIFT_DIY_PORT/'$OPENSHIFT_DIY_PORT'/' $CATALINA_HOME/conf/server.xml




