#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x

if [ ! -e $OPENSHIFT_DATA_DIR/app.initialized ]; then
    mysql --user=$OPENSHIFT_MYSQL_DB_USERNAME --password=$OPENSHIFT_MYSQL_DB_PASSWORD --host=$OPENSHIFT_MYSQL_DB_HOST --port=$OPENSHIFT_MYSQL_DB_PORT --database=$OPENSHIFT_APP_NAME < $OPENSHIFT_REPO_DIR/init/init-db.sql

    mkdir -p $OPENSHIFT_DATA_DIR/axel
    cp -r $OPENSHIFT_REPO_DIR/init/images $OPENSHIFT_DATA_DIR/axel

    sed -ig 's/OPENSHIFT_DATA_DIR/'$OPENSHIFT_DATA_DIR'/' $OPENSHIFT_JBOSSEWS_DIR/conf/server.xml

    touch $OPENSHIFT_DATA_DIR/app.initialized
fi



