#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.7.0_75
export CATALINA_HOME=$OPENSHIFT_DATA_DIR/apache-tomcat-8.0.21

cd $OPENSHIFT_REPO_DIR

export CATALINA_OPTS="-Dconfiguration.profile=rhc -Duser.timezone=UTC"
#export JPDA_ADDRESS=$OPENSHIFT_DIY_IP:8000

#$CATALINA_HOME/bin/catalina.sh jpda start
$CATALINA_HOME/bin/catalina.sh start
